#!/bin/bash

#
# serf        serf startup script
#
# chkconfig: - 85 15
# processname: serf
# description: serf agent
#

# Source function library.
. /etc/rc.d/init.d/functions

NAME="serf"
BIN="/usr/local/bin/$NAME"
EVENT_HANDLER="/etc/$NAME/handlers/router.sh"
LOGLEVEL="info"
LOGFILE="/var/log/$NAME.log"
CMD="$BIN agent -log-level=$LOGLEVEL -event-handler $EVENT_HANDLER"

PGREP="/usr/bin/pgrep -f"

RETVAL=0

start() {
	echo -n "$NAME starting... "
	$CMD 2>&1 >> $LOGFILE &
	RETVAL=$?
	echo "[ok]"
}

status() {
	PIDS=$($PGREP "$CMD" | xargs)
	if [ "$PIDS" == "" ]; then
		echo "$NAME not running!"
	else
		echo "$NAME running... [ $PIDS ]"
	fi
}

stop() {
	PIDS=$($PGREP "$CMD" | xargs)
	for PID in PIDS; do
		echo -n "$NAME stopping... "
		kill $PID
		echo "[ok]"
	done
	RETVAL=$?
}

case "$1" in 
	start)
		start;
		;;
	stop)
		stop;
		;;
	restart)
		stop
		start
		;;
	status)
		status
		;;
	*)
		echo "$0 [ start | stop | restart | status ]"
		;;
esac
exit $RETVAL