#!/bin/bash

#
# serf        serf startup script
#
# chkconfig: - 85 15
# processname: serf
# description: serf agent
#
NAME="serf"
BIN="/usr/local/bin/$NAME"
LOGLEVEL="info"
LOGFILE="/var/log/$NAME.log"

# Source function library.
. /etc/rc.d/init.d/functions

# sysconfig settings
[ -f "/etc/sysconfig/$NAME" ] && . /etc/sysconfig/$NAME

SERF_EVENT_HANDLER="/etc/$NAME/handlers/router.sh"
SERF_CMD="$BIN agent -log-level=$LOGLEVEL -event-handler $SERF_EVENT_HANDLER -join $SERF_JOIN_NODE"

PGREP="/usr/bin/pgrep -f"

RETVAL=0

start() {
	echo -n "$NAME starting... "
	$SERF_CMD 2>&1 >> $LOGFILE &
	RETVAL=$?
	echo "[ok]"
}

status() {
	PIDS=$($PGREP "$SERF_CMD" | xargs)
	if [ "$PIDS" == "" ]; then
		echo "$NAME not running!"
	else
		echo "$NAME running... [ $PIDS ]"
		$BIN members
	fi
}

stop() {
	PIDS=$($PGREP "$SERF_CMD" | xargs)
	echo -n "$NAME stopping... "
	for PID in $PIDS; do
		kill $PID
	done
	echo "[ok]"
	RETVAL=$?
}

case "$1" in 
	start)
		start;
		;;
	stop)
		stop;
		;;
	restart)
		stop
		start
		;;
	status)
		status
		;;
	*)
		echo "$0 [ start | stop | restart | status ]"
		;;
esac
exit $RETVAL
